import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Mi Informe",
    short_name: "Mi Informe",
    description: "Registro de actividad y progreso de servicio del campo",
    start_url: "/panel",
    display: "standalone",
    background_color: "#f9f9fb",
    theme_color: "#f9f9fb",
    icons: [
      {
        // Route generated by src/app/apple-icon.tsx (there is no /apple-icon.png file).
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  };
}
